/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/views/AboutView.vue')['default']
    AmazingFeaturesSection: typeof import('./src/components/AmazingFeaturesSection.vue')['default']
    AppBar: typeof import('./src/components/app/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AwardWinningSection: typeof import('./src/components/AwardWinningSection.vue')['default']
    ContactUsSection: typeof import('./src/components/ContactUsSection.vue')['default']
    CustomizeSection: typeof import('./src/components/CustomizeSection.vue')['default']
    DiscoverHelp: typeof import('./src/components/DiscoverHelp.vue')['default']
    FAQSection: typeof import('./src/components/FAQSection.vue')['default']
    Footer: typeof import('./src/components/app/AppFooter.vue')['default']
    FunFactsSection: typeof import('./src/components/FunFactsSection.vue')['default']
    LandingSection: typeof import('./src/components/LandingSection.vue')['default']
    LogoSection: typeof import('./src/components/LogoSection.vue')['default']
    MeetOurTeamSection: typeof import('./src/components/MeetOurTeamSection.vue')['default']
    OurPortfolioSection: typeof import('./src/components/OurPortfolioSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhatPeopleSaySection: typeof import('./src/components/WhatPeopleSaySection.vue')['default']
    WhatWeDoSection: typeof import('./src/components/WhatWeDoSection.vue')['default']
  }
}
